version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: tarot-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-tarot}
      POSTGRES_USER: ${DB_USER:-tarot-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-fn5YW95BMyL}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-tarot-admin} -d ${DB_NAME:-tarot}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
